# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-14 01:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 10, 14, 1, 1, 53, 462580, tzinfo=utc), verbose_name='Post date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogindexpage',
            name='intro',
            field=models.CharField(max_length=250),
        ),
    ]
